// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:main.NodeConfig):Promise<main.ConnectionStatus>;

export function Disconnect():Promise<main.ConnectionStatus>;

export function GetStatus():Promise<main.ConnectionStatus>;
